ssh:
  # SSH user is set to postgres for allowing access for pg_ctl and postgres server
  # while the PostgresqlDB.user refers to the user of the database accessing data
  pg_user_name: postgres
  pg_user_pwd: '741286'

database:
  db_host: localhost
  db_port: '5432'
  db_user_name: viktor
  db_passwd: '741286'
  db_name: tpch

  pg_ctl: /usr/lib/postgresql/14/bin/pg_ctl
  pg_data: /var/lib/postgresql/14/main
  pg_server: /usr/lib/postgresql/14/bin/postgres
  pg_conf: /var/lib/postgresql/experiment/conf/tune_cnf.conf
  pg_sock: /var/run/postgresql/.s.PGSQL.543

  remote_mode: false
  online_mode: false
  exec_mode: raw
  perf_name: total_exec_time
  perf_unit: s

  benchmark: TPCH
  benchmark_fast: true # only execute short queries
  use_pgbench: false

  # saved locally
  knob_definitions: selected.json
  knob_num: -1

  
  negate: true

tune:
  seed: 1
  num_evals: 10
  batch_size: 1
  extern_init: false

  optimizer: mcts
  optimizer_params:
    global_num_init: 4
    local_num_init: 2
    local_optimizer_type: turbo
