expr_name: GPBO_ackley_20

strategy: gp-bo
seed: 1024
is_minimizing: True
computation_budget: 500
batch_size: 1
acquisition: 'ei'

init_design: sobol
num_init: 20

benchmark: ackley
benchmark_params:
  dim: 20
  noise_std: null
  negate: False
  bounds: null